<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findarchiv()
    {
        $query = $this->getEntityManager()->createQuery("SELECT p FROM ReclamationBundle:Reclamation p WHERE p.date BETWEEN CURRENT_DATE() AND (CURRENT_DATE() -30)  ");
        return $query->getResult();
    }
}
