<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findarchiv()
    {
        $query = $this->getEntityManager()->createQuery("SELECT * FROM `reclamation` WHERE CURRENT_DATE-date> 30 AND etat='traité'");
        var_dump($query->getResult());
        return $query->getMaxResults();
    }

    public function findAjax($search)
    {

        return $this->createQueryBuilder('e')
            ->andWhere('e.sujet LIKE :sujet')
            ->setParameter('sujet','%' .$search . '%')
            ->getQuery()
            ->getResult();
    }
}
