<?php

namespace Allforkids\UserBundle\Repository;

/**
 * GuardianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuardianRepository extends \Doctrine\ORM\EntityRepository
{
}
