shop_homepage:
    path:     /products
    defaults: { _controller: shopBundle:Default:index }
Affichage_prod_solo:
    path:     /products/{id}
    defaults: { _controller: shopBundle:Default:viewProd }
shop_cart:
    path:     /shoppingcart
    defaults: { _controller: shopBundle:ShoppingCart:index }
add_wishlist:
    path:     /wishlist/{id}
    defaults: { _controller: shopBundle:ShoppingCart:addwishlist }
shopping_basket_add:
    path:     /addcart/{id}
    defaults: { _controller: shopBundle:ShoppingCart:addToBasket}
shopping_basket_delete:
    path:     /suppcmd/{id}
    defaults: { _controller: shopBundle:ShoppingCart:suppCmd}
show_wishlist:
    path:     /wishlist
    defaults: { _controller: shopBundle:ShoppingCart:wishlist }
show_wishlist_parent:
    path:     /wishlistparent
    defaults: { _controller: shopBundle:Default:wishlistParent }