reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }
ajoutR:
    path:     /Ajout
    defaults: { _controller: ReclamationBundle:Reclamation:Ajout }
ListR:
    path:     /Affichage
    defaults: { _controller: ReclamationBundle:Reclamation:show }

DeleteR:
    path:     /Delete/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Delete }
UpdateR:
    path:     /Update/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Update }
RechercheR:
    path:     /RechercheR
    defaults: { _controller: ReclamationBundle:Reclamation:Recherch }
ListRadmin:
    path:     /Affichageadmin
    defaults: { _controller: ReclamationBundle:Reclamation:showAdmin }
UpdateEtat:
    path:     /Update/{id}/{name}
    defaults: { _controller: ReclamationBundle:Reclamation:Updateetat }
detail:
    path:     /details/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:afficheE}
RecherchReclamation:
    path:     /Recherche
    defaults: { _controller: ReclamationBundle:Reclamation:filter}
Archive:
    path:     /Archive
    defaults: { _controller: ReclamationBundle:Reclamation:archiver}



