reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }
ajoutR:
    path:     /Ajout
    defaults: { _controller: ReclamationBundle:Reclamation:Ajout }
ListR:
    path:     /Affichage
    defaults: { _controller: ReclamationBundle:Reclamation:show }

DeleteR:
    path:     /Delete/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Delete }
UpdateR:
    path:     /Update/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Update }
RechercheR:
    path:     /RechercheR
    defaults: { _controller: ReclamationBundle:Reclamation:Recherch }
ListRadmin:
    path:     /Affichageadmin
    defaults: { _controller: ReclamationBundle:Reclamation:showAdmin }
UpdateEtat:
    path:     /Update/{id}/{name}
    defaults: { _controller: ReclamationBundle:Reclamation:Updateetat }
detail:
    path:     /details/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:afficheE}
RecherchReclamation:
    path:     /Recherche
    defaults: { _controller: ReclamationBundle:Reclamation:recherche}
Archive:
    path:     /Archive
    defaults: { _controller: ReclamationBundle:Reclamation:archiver}

ajoutmsg:
    path:     /AjoutMsg
    defaults: { _controller: ReclamationBundle:Reclamation:AjoutMessage }
ListMesg:
    path:     /ListMsg
    defaults: { _controller: ReclamationBundle:Reclamation:showMessage }
Deletemsg:
    path:     /DeleteMsg/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Deletemsg }

_ajax:
        path: /recherche/search
        defaults: { _controller: ReclamationBundle:Reclamation:rechercheAjax}
ajoutC:
    path:     /AjoutC
    defaults: { _controller: ReclamationBundle:Reclamation:AjoutCours }

Listc:
    path:     /Affichagec
    defaults: { _controller: ReclamationBundle:Reclamation:affichecours }
Listcd:
    path:     /Affichagecdetails/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Affichagecdetails }
AffichageMsg:
    path:     /Affichagemessage
    defaults: { _controller: ReclamationBundle:Reclamation:affichemessage }

print:
    path:     /printpdf/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:toPdf }
rech:
    path:     /search
    defaults: { _controller: ReclamationBundle:Reclamation:serch}
multi:
      path:     /multiserch
      defaults: { _controller: ReclamationBundle:Reclamation:multisearch}
annuler:
      path:     /Annuler
      defaults: { _controller: ReclamationBundle:Reclamation:annuler}
